installRoot:
	make installNeovim installChisel
	
installUser:
	cd ./util && source ./copy_vim_setup.sh

updateNeovim:
	cd ./util && source ./copy_vim_setup.sh

installNeovim:
	cd ./util &&\
		source ./install_neovim.sh

installChisel:
	cd ./util &&\
		source ./install_chisel.sh
